# Generated by Django 5.2.17 on 2026-09-27 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المصدر')),
                ('edition', models.CharField(blank=True, max_length=200, verbose_name='الطبعة أو نظام الترقيم')),
                ('license', models.CharField(blank=True, max_length=200, verbose_name='الترخيص')),
                ('url', models.URLField(blank=True, verbose_name='رابط المصدر')),
            ],
            options={
                'verbose_name': 'مصدر',
                'verbose_name_plural': 'المصادر',
                'unique_together': {('name', 'edition')},
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quran', 'آية'), ('hadith', 'حديث'), ('athar', 'أثر أو قول')], max_length=10)),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='الرقم')),
                ('text', models.TextField(verbose_name='النص')),
                ('text_norm', models.TextField(editable=False)),
                ('grade', models.CharField(blank=True, max_length=200, verbose_name='الحكم كما ورد')),
                ('grade_class', models.CharField(choices=[('quran', 'قرآن'), ('sahih', 'صحيح'), ('hasan', 'حسن'), ('daif', 'ضعيف'), ('mawdu', 'موضوع'), ('la_asl', 'لا أصل له'), ('misattributed', 'منسوب خطأً')], max_length=15)),
                ('grader', models.CharField(blank=True, max_length=200, verbose_name='الحاكم')),
                ('grade_ref', models.CharField(blank=True, max_length=300, verbose_name='مرجع الحكم')),
                ('other_grades', models.JSONField(blank=True, default=list)),
                ('actual_attribution', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True, verbose_name='رابط التحقق')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='texts', to='verifier.source')),
            ],
            options={
                'verbose_name': 'نص',
                'verbose_name_plural': 'النصوص',
            },
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim', models.TextField()),
                ('verdict', models.CharField(max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reviewer_note', models.TextField(blank=True)),
                ('matched_text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verifier.text')),
            ],
            options={
                'verbose_name': 'بلاغ خطأ',
                'verbose_name_plural': 'بلاغات الأخطاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='text',
            index=models.Index(fields=['grade_class'], name='verifier_te_grade_c_40e64d_idx'),
        ),
    ]
