# Generated by Django 5.2.17 on 2026-10-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: DeepSeek، OpenAI GPT-4o، Claude Sonnet', max_length=100, verbose_name='الاسم المعروض')),
                ('api_style', models.CharField(choices=[('openai', 'متوافق مع OpenAI (DeepSeek/OpenAI/Groq/Mistral/Gemini...)'), ('anthropic', 'Anthropic (Claude)')], default='openai', max_length=10, verbose_name='نمط الـ API')),
                ('model', models.CharField(help_text='مثال: deepseek-chat، gpt-4o، gemini-3.1-flash-lite', max_length=150, verbose_name='اسم النموذج (model)')),
                ('base_url', models.URLField(blank=True, help_text='إلزامي لـ «متوافق مع OpenAI» (مثال: https://api.deepseek.com). اتركه فارغاً لـ Anthropic.', verbose_name='رابط الـ API')),
                ('api_key', models.CharField(blank=True, help_text='يُخزّن كنص في قاعدة البيانات. الأفضل استعمال متغير بيئة (الحقل التالي).', max_length=500, verbose_name='مفتاح API')),
                ('api_key_env', models.CharField(blank=True, help_text='مثال: GEMINI_API_KEY. إن مُلئ يُقدَّم على المفتاح المخزّن.', max_length=100, verbose_name='اسم متغير البيئة للمفتاح')),
                ('use_for_extraction', models.BooleanField(default=True, verbose_name='يُستعمل لاستخراج النصوص')),
                ('use_for_baseline', models.BooleanField(default=False, verbose_name='يُستعمل نموذجاً مرجعياً في التقييم')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('priority', models.IntegerField(default=100, help_text='الأصغر يُجرَّب أولاً، والباقي احتياط عند الفشل.', verbose_name='الأولوية')),
                ('timeout', models.PositiveIntegerField(default=60, verbose_name='مهلة الاتصال (ثانية)')),
                ('last_test_ok', models.BooleanField(editable=False, null=True)),
                ('last_test_message', models.CharField(blank=True, editable=False, max_length=500)),
            ],
            options={
                'verbose_name': 'نموذج ذكاء اصطناعي',
                'verbose_name_plural': 'نماذج الذكاء الاصطناعي',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DorarCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500, unique=True)),
                ('results', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ذاكرة الدرر المؤقتة',
                'verbose_name_plural': 'ذاكرة الدرر المؤقتة',
            },
        ),
        migrations.CreateModel(
            name='GradeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200, verbose_name='العبارة')),
                ('phrase_norm', models.CharField(db_index=True, editable=False, max_length=200)),
                ('match_type', models.CharField(choices=[('exact', 'مطابقة تامة'), ('contains', 'تحتوي العبارة')], default='exact', max_length=10, verbose_name='طريقة المطابقة')),
                ('grade_class', models.CharField(choices=[('quran', 'قرآن'), ('sahih', 'صحيح'), ('hasan', 'حسن'), ('daif', 'ضعيف'), ('mawdu', 'موضوع'), ('la_asl', 'لا أصل له'), ('misattributed', 'منسوب خطأً'), ('isnad', 'حكم على الإسناد فقط')], max_length=15, verbose_name='التصنيف')),
                ('priority', models.IntegerField(default=100, help_text='الأصغر يُفحص أولاً. ضع العبارات الأطول والأخص أولاً، مثل «إسناده صحيح» قبل «صحيح».', verbose_name='الأولوية')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='ملاحظة')),
                ('reviewed', models.BooleanField(default=False, verbose_name='تمت مراجعته')),
            ],
            options={
                'verbose_name': 'تحويل حكم',
                'verbose_name_plural': 'جدول تحويل الأحكام',
                'ordering': ['priority', '-match_type'],
            },
        ),
        migrations.AlterField(
            model_name='text',
            name='grade_class',
            field=models.CharField(choices=[('quran', 'قرآن'), ('sahih', 'صحيح'), ('hasan', 'حسن'), ('daif', 'ضعيف'), ('mawdu', 'موضوع'), ('la_asl', 'لا أصل له'), ('misattributed', 'منسوب خطأً'), ('isnad', 'حكم على الإسناد فقط')], max_length=15),
        ),
    ]
