# Generated by Django 5.2.17 on 2026-10-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0002_aiprovider_dorarcache_grademapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='chapter',
            field=models.CharField(blank=True, max_length=500, verbose_name='الكتاب والباب'),
        ),
        migrations.AlterField(
            model_name='grademapping',
            name='grade_class',
            field=models.CharField(choices=[('quran', 'قرآن'), ('sahih', 'صحيح'), ('hasan', 'حسن'), ('daif', 'ضعيف'), ('mawdu', 'موضوع'), ('la_asl', 'لا أصل له'), ('misattributed', 'منسوب خطأً'), ('isnad', 'حكم على الإسناد فقط'), ('ungraded', 'مروي دون حكم')], max_length=15, verbose_name='التصنيف'),
        ),
        migrations.AlterField(
            model_name='text',
            name='grade_class',
            field=models.CharField(choices=[('quran', 'قرآن'), ('sahih', 'صحيح'), ('hasan', 'حسن'), ('daif', 'ضعيف'), ('mawdu', 'موضوع'), ('la_asl', 'لا أصل له'), ('misattributed', 'منسوب خطأً'), ('isnad', 'حكم على الإسناد فقط'), ('ungraded', 'مروي دون حكم')], max_length=15),
        ),
    ]
