# Generated by Django 5.2.17 on 2026-10-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0003_text_chapter_alter_grademapping_grade_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedGrader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: الألباني', max_length=100, verbose_name='الاسم المعروض')),
                ('aliases', models.CharField(blank=True, help_text='مفصولة بفاصلة، مثل: الارناؤوط، الأرنؤوط', max_length=300, verbose_name='صيغ الاسم في المصادر')),
                ('priority', models.IntegerField(default=100, verbose_name='الترتيب في الخلاصة')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
            ],
            options={
                'verbose_name': 'محدّث معتمد',
                'verbose_name_plural': 'المحدّثون المعتمدون',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
