# Generated by Django 5.2.17 on 2026-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0005_seed_trusted_graders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Narrator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='rawi_index')),
                ('name', models.TextField(verbose_name='الاسم')),
                ('grade', models.TextField(blank=True, verbose_name='الدرجة')),
                ('tone', models.CharField(choices=[('thiqa', 'ثقة'), ('saduq', 'صدوق'), ('weak', 'ضعيف'), ('unknown', 'غير مصنّف')], default='unknown', max_length=10)),
            ],
            options={
                'verbose_name': 'راوٍ',
                'verbose_name_plural': 'الرواة',
            },
        ),
        migrations.AddField(
            model_name='text',
            name='asaneed',
            field=models.JSONField(blank=True, default=list, help_text='قوائم معرّفات الرواة، من الصحابي إلى صاحب الكتاب', verbose_name='الأسانيد'),
        ),
        migrations.AddField(
            model_name='text',
            name='ext_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='معرّف القاعدة (hadithID)'),
        ),
        migrations.AddField(
            model_name='text',
            name='full_text',
            field=models.TextField(blank=True, verbose_name='النص بإسناده'),
        ),
        migrations.AddField(
            model_name='text',
            name='searchable',
            field=models.BooleanField(default=True, help_text='روايات الإسناد بلا متن مستقل تُحفظ للمتخصصين ولا تُفهرس', verbose_name='يدخل في البحث'),
        ),
        migrations.AddField(
            model_name='text',
            name='takhreeg',
            field=models.JSONField(blank=True, default=list, help_text='معرّفات القاعدة (hadithID) لمواضع الحديث في الكتب الأخرى', verbose_name='التخريج'),
        ),
    ]
