# Generated by Django 5.2.17 on 2026-10-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifier', '0006_specialist_isnad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrator',
            name='tone',
            field=models.CharField(choices=[('thiqa', 'ثقة أو صحابي'), ('saduq', 'صدوق'), ('majhul', 'مجهول أو مستور'), ('weak', 'ضعيف'), ('unknown', 'غير مصنّف')], default='unknown', max_length=10),
        ),
    ]
